name: Deploy SMTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest 

    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/sources/smtp-server

            cat > .env << EOF
            SMTP_PORT=${{ secrets.SMTP_PORT }}
            API_URL=${{ secrets.API_URL }}
            EOF
            
            git pull origin main
            npm ci
            pm2 restart smtp-server
            